<?php

declare(strict_types=1);

namespace JardisTools\DevSkills\Tests\Integration\Handler\Validate;

use Composer\Util\Filesystem;
use JardisTools\DevSkills\Data\RenamedSkills;
use JardisTools\DevSkills\Data\SkillDescriptor;
use JardisTools\DevSkills\Handler\Install\BuildRedirectSkill;
use JardisTools\DevSkills\Handler\Validate\CheckRuleMarkers;
use JardisTools\DevSkills\Handler\Validate\CheckSkillLinks;
use JardisTools\DevSkills\Handler\Validate\ValidateSkillMd;
use JardisTools\DevSkills\Tests\Support\TempProject;
use PHPUnit\Framework\TestCase;

/**
 * Redirect skills (generated by BuildRedirectSkill for every renamed bundle
 * skill) must pass the complete validator chain: format, links and rule markers.
 */
final class RedirectSkillsValidationTest extends TestCase
{
    private TempProject $project;

    protected function setUp(): void
    {
        $this->project = new TempProject('dev-skills-redirect-validate-');
    }

    protected function tearDown(): void
    {
        $this->project->cleanup();
    }

    public function testEveryRedirectSkillPassesFormatLinksAndRuleMarkers(): void
    {
        $build = new BuildRedirectSkill(new Filesystem());
        foreach (array_keys(RenamedSkills::MAPPING) as $old) {
            $build(new SkillDescriptor($old, '', 'jardis/dev-skills'), $this->project->path('skills/' . $old));
        }

        $failures = [];
        foreach (array_keys(RenamedSkills::MAPPING) as $old) {
            $file   = $this->project->path('skills/' . $old . '/SKILL.md');
            $errors = [...(new ValidateSkillMd())($file), ...(new CheckSkillLinks())($file)];
            if ($errors !== []) {
                $failures[$old] = $errors;
            }
        }
        $failures += (new CheckRuleMarkers())(
            $this->project->path('skills'),
            array_keys(RenamedSkills::MAPPING),
        );

        self::assertSame([], $failures, print_r($failures, true));
    }
}
